CREATE FUNCTION play_badapple() RETURNS void
AS 'MODULE_PATHNAME'
LANGUAGE C STRICT;

CREATE FUNCTION play_basketball() RETURNS void
AS 'MODULE_PATHNAME'
LANGUAGE C STRICT;

CREATE FUNCTION play_anything(path text, nline int) RETURNS void
AS 'MODULE_PATHNAME'
LANGUAGE C STRICT;